<a href="https://colab.research.google.com/github/shivshankarsajeev/PyTorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:


if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.6179, 0.5736, 0.1040],
        [0.6600, 0.7324, 0.1346]])

In [8]:
# use of seed
torch.rand(2,3)

tensor([[0.3941, 0.4455, 0.6185],
        [0.7601, 0.7359, 0.1016]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [16]:
# copy the shape of x
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3833749897349314868]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [22]:
# find data type
x.dtype

torch.float32

In [23]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
# using to()
x.to(torch.float32)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [26]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [27]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

### 2. Element wise operation

In [28]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [29]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

In [30]:
c = torch.tensor([1, -2, 3, -4])

In [31]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [32]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [33]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [34]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [35]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [36]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [37]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [51]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[9., 7., 5.],
        [9., 8., 9.]])

In [46]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([ 9., 21.])

In [47]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([5.5000, 2.5000, 7.0000])

In [48]:
# median
torch.median(e)

tensor(5.)

In [53]:
# max and min
torch.max(e)
torch.min(e)

tensor(5.)

In [52]:
# product
torch.prod(e)

tensor(204120.)

In [54]:
# standard deviation
torch.std(e)

tensor(1.6021)

In [55]:
# variance
torch.var(e)

tensor(2.5667)

In [56]:
# argmax
torch.argmax(e)

tensor(0)

In [57]:
# argmin
torch.argmin(e)

tensor(2)

### 4. Matrix operations

In [58]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3],
        [6, 1],
        [5, 5]])


In [59]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[120,  40],
        [125,  60]])

In [60]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [61]:
# transpose
torch.transpose(f, 0, 1)

tensor([[7, 6],
        [9, 7],
        [2, 7]])

In [62]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 4., 3.],
        [8., 8., 3.],
        [3., 5., 0.]])

In [63]:
# determinant
torch.det(h)

tensor(84.)

In [64]:
# inverse
torch.inverse(h)

tensor([[-0.1786,  0.1786, -0.1429],
        [ 0.1071, -0.1071,  0.2857],
        [ 0.1905,  0.1429, -0.3810]])

### 5. Comparison operations

In [65]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[6, 4, 0],
        [8, 4, 7]])
tensor([[2, 3, 8],
        [5, 6, 2]])


In [68]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[False, False,  True],
        [False,  True, False]])

### 6. Special functions

In [69]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[9., 5., 0.],
        [4., 2., 7.]])

In [70]:
# log
torch.log(k)

tensor([[2.1972, 1.6094,   -inf],
        [1.3863, 0.6931, 1.9459]])

In [71]:
# exp
torch.exp(k)

tensor([[8.1031e+03, 1.4841e+02, 1.0000e+00],
        [5.4598e+01, 7.3891e+00, 1.0966e+03]])

In [72]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 2.2361, 0.0000],
        [2.0000, 1.4142, 2.6458]])

In [73]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.9933, 0.5000],
        [0.9820, 0.8808, 0.9991]])

In [74]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.9331e-01, 9.5257e-01, 9.1105e-04],
        [6.6929e-03, 4.7426e-02, 9.9909e-01]])

In [75]:
# relu
torch.relu(k)

tensor([[9., 5., 0.],
        [4., 2., 7.]])

## Inplace Operations  (_)

In [79]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])
tensor([[0.6269, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])


In [80]:
# When we perform m + n result tensor will be stored in new memory so in order to avoid this
m.add_(n)

tensor([[1.0504, 1.3501, 1.0769],
        [0.1227, 1.4047, 0.8966]])

In [81]:
m

tensor([[1.0504, 1.3501, 1.0769],
        [0.1227, 1.4047, 0.8966]])

In [82]:
n

tensor([[0.6269, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])

In [83]:
torch.relu(m)

tensor([[1.0504, 1.3501, 1.0769],
        [0.1227, 1.4047, 0.8966]])

In [84]:
m.relu_()

tensor([[1.0504, 1.3501, 1.0769],
        [0.1227, 1.4047, 0.8966]])

In [ ]:
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

## Copying a Tensor

In [85]:
a = torch.rand(2,3)
a

tensor([[0.7340, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [86]:
b = a

In [87]:
b

tensor([[0.7340, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [88]:
a[0][0] = 0

In [89]:
a

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [90]:
b

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [91]:
id(a)

133384595937360

In [92]:
id(b)

133384595937360

In [93]:
b = a.clone()

In [94]:
a

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [95]:
b

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [96]:
a[0][0] = 10

In [97]:
a

tensor([[10.0000,  0.8497,  0.9112],
        [ 0.4847,  0.9436,  0.3904]])

In [98]:
b

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [99]:
id(a)

133384595937360

In [100]:
id(b)

133384814067632

In [102]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [103]:
device = torch.device('cuda')

In [104]:
# creating a new tensor on GPU
torch.rand(2,3, device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [105]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.2499, 0.3206, 0.9753],
        [0.7582, 0.6688, 0.2651]])

In [106]:
b = a.to(device)

In [107]:
b+5

tensor([[5.2499, 5.3206, 5.9753],
        [5.7582, 5.6688, 5.2651]], device='cuda:0')

## CPU vs GPU

In [113]:
import time

# Define the size of the matrix
size = 10000

# create random matirx on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure the time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU:m {cpu_time:.4f} seconds")


# create random matirx on GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu1.to('cuda')

# Measure the time on CPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize() # Ensure all GPU operation are complete
gpu_time = time.time() - start_time

print(f"Time on CPU:m {gpu_time:.4f} seconds")

Time on CPU:m 24.7447 seconds
Time on CPU:m 0.5241 seconds


## Reshaping Tensor

In [115]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [116]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [118]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
b = torch.rand(2,3,4)
b

tensor([[[0.9523, 0.7858, 0.8132, 0.2798],
         [0.1631, 0.7686, 0.0762, 0.5738],
         [0.3494, 0.6589, 0.6317, 0.5781]],

        [[0.1440, 0.7407, 0.2540, 0.0781],
         [0.8851, 0.5333, 0.1254, 0.5378],
         [0.3836, 0.8841, 0.2012, 0.4210]]])

In [121]:
# permute

b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [124]:
# unsqueeze
c = torch.rand(226, 226, 3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [125]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy vs Tensor

In [126]:
import numpy as np

In [127]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [128]:
b = a.numpy()

In [129]:
b

array([1, 2, 3])

In [130]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [131]:
torch.from_numpy(c)

tensor([1, 2, 3])